### ISSUE TITLE
Fix system spec for editing and deleting posts

### ISSUE THREAD

**Issue by riggraz** [riggraz/astuto#210]
1. The spec `lets edit the post` of `spec/system/post_spec.rb` fails but I don't know why.
2. The spec `lets delete the post` is fragile: sometimes it passes, sometimes it fails.

They should be fixed.

**Comment by riggraz** [comment]
The `lets delete the post` spec sometimes fails with this error:
```
1) post lets delete the post
     Failure/Error: @board = Board.find(params[:id])

     ActiveRecord::RecordNotFound:
       Couldn't find Board with 'id'=0 [WHERE "boards"."tenant_id" = $1]



     # ./app/controllers/boards_controller.rb:13:in `show'
     # ------------------
     # --- Caused by: ---
     # Capybara::ExpectationNotMet:
     #   expected "/posts/[10](https://github.com/astuto/astuto/actions/runs/4901814449/jobs/8753291808#step:9:11)6" to equal "/boards/70"
     #   ./spec/system/post_spec.rb:99:in `block (2 levels) in <main>'
```
